# Default, Defaults
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: Blooming Procrastination
email: mycielo91@gmail.com
description: A small programming journal
baseurl: "/home" # the subpath of your site, e.g. /blog

# Where can people find your site?
url: ""
# When developing, set this ^ equal to whatever localhost you're using

# Social Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

author: Jamie Minyoung Kim
authorBio: Previously a title designer based in Los Angeles, CA, now learning C++/C programming.
